name: Scheduled PR Merge

on:
  schedule:
    - cron: '35 19 11 4 *'  # UTC time: April 11, 2025 at 7:35 PM

jobs:
  merge-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Merge PR #1
        uses: peter-evans/merge-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request: 1
          merge-method: squash
